mine = [
'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
'XXXXXXXXXXXXXXXXXX                                                                                                ',
'XXXXXXXXXXXXXXXXXX                                                                                                ',
'XXXXXXXXXXXXXXXXXX                                                                                                ',
'XXXXXXXXXXXXXXXXXX                                                                                                ',
'XXXXXXXXXXXXXXXXXX                                                  XX                                            ',
'XXXXXXXXXXXXXXXXXX                                                XXXXX                                           ',
'                                  S             XXS             XXXXXXXX                                          ',
'             M       P            XXX         XXXXXX             XXXXXXXX                            T            ',
'XXXXXXXXXXXXXXXXXXXXXXXXXX      XXXXXXX        XXXXX       XX       XXXXX                          XXX            ',
'XXXXXXXXXXXXXXXXXXXXXXXXXX    XXXXXXXXXXXX       XX     S XXXX                                  XXXXXX            ',
'XXXXXXXXXXXXXXXXXXXXXXX        XXXXXXXXX                XXXXX                                XXXXXXXXX            ',
'XXXXXXXXXXXXXXXXXXXX            XXXX         XX          XXX         S                   XXXXXXXXXXXXX            ',
'XXXXXXXXXXXXXXXXXX                          XXXXX                    XX              XXXXXXXXXXXXXXXX             ',
'XXXXXXXXXXXXXXXXXX                            XXX                   XXXX   XXXXXXXXXXXXXXXXXXXXXXXX               ',
'XXXXXXXXXXXXXXXXXX                                    XXS          XXXXX     XXXXXXXXXXXXXXXXXXXX                 ',
'XXXXXXXXXXXXXXXXXX          S                        XXXXX   S     XXX         XXXXXXXXXXXXXXXXX                  ',
'XXXXXXXXXXXXXXXXXX         XXXXX      XXS            XXXXX   XX                  XXXXXXXXXXXXX                    ',
'XXXXXXXXXXXXXXXXXX       XXXXXXXX    XXXXXX           XXX   XXXX                   XXXXXXXXX                      ',
'XXXXXXXXXXXXXXXXXX       XXXXXXXXXXXXXXXXXXX     S          XXXXXX                  XXXXXXX                       ',
'XXXXXXXXXXXXXXXXXX           XXXX     XXXXXX     XXX         XXX                     XXXXX                        ',
'XXXXXXXXXXXXXXXXXX             XX     XXX       XXXXX                                                             ',
'XXXXXXXXXXXXXXXXXX                                 XX                                                             ',
'XXXXXXXXXXXXXXXXXX                                                                                                ',
]

starting = [
'                                         XXXXXXXXXXXXXXXXXXXXX',
'                                         XXXXXXXXXXXXXXXXXXXXX',
'                                         XXXXXXXXXXXXXXXXXXXXX',
'                                         XXXXXXXXXXXXXXXXXXXXX',
'                                         XXXXXXXXXXXXXXXXXXXXX',
'                                                              ',
'                            W                M                ',
'      P                         XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
'                        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
'     XXXX          XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX ',
'   XXXXXXXX       XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX ',
'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX ',
'XXXXXXXXXXXX       XXXXXXXXXXXXX  XXXXXX    XXXX  XXXXXX      ',
'XXXXXXXXX          XXXXXXXXXXX     XXXX      XX               ',
'  XXX                 XXXXXXX       XXX                       ',
'                         XXX                                  ',
]

second = [
'                                                             T',
'                                         XXXXXXXXXXXXXXXXXXXXX',
'                                         XXXXXXXXXXXXXXXXXXXXX',
'                                         XXXXXXXXXXXXXXXXXXXXX',
'                                         XXXXXXXXXXXXXXXXXXXXX',
'                                         XXXXXXXXXXXXXXXXXXXXX',
'                                           X                  ',
'                            W        P     X M                ',
'                                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
'                        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
'     XXXX          XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX ',
'   XXXXXXXX       XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX ',
'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX ',
'XXXXXXXXXXXX       XXXXXXXXXXXXX  XXXXXX    XXXX  XXXXXX      ',
'XXXXXXXXX          XXXXXXXXXXX     XXXX      XX               ',
'  XXX                 XXXXXXX       XXX                       ',
'                         XXX                                  ',
]

third = [
'                     XXX                                                      ',
' XXXXX       D        XXX             D                                       ',
'  XXXXXX                                           XXX                D       ',
'    XXX                          XX                XXXX                       ',
'                   D       XX   XXX     XXXX        XX                        ',
'                          XXXXXXXXXXXXXXXXXX         X      D                 ',
'            XX               XX         XXXX                               D  ',
'             XXXXXX              D      XX                                    ',
'              XXXX                                                            ',
'                                     D                 XX                     ',
'                                             D        XXXXX                   ',
'                                           XXXXXXXXXXXXXX                     ',
'  XXX P                                XXXXXX        XXX                      ',
'  XXXXXXXXXX                          D  XXXX         XX                      ',
'XXXX    XXXXX           XX       XX       XX                                T ',
'          XXX        XXXXXXXXXXXXXXX                               D    XXXXX ',
'                      XX      XXX                        D        XXXXXXXXXXX ',
'                                                           XXXXXXXXXXXXXXXXXX ',
'                                             XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX ',
'               XXXXX            D             XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX ',
'            XXXXXX                               XXXXXXXXXXXXXXXXXXXXXXXXXXXX ',
' D            XX                                    XXXXXXXXXXXXXXXXXXXXX     ',
'   XX                    D            D  XXXX         XXXXXXXXXXXXXXXX        ',
'  XXXX                   XX               XXXXXXX          XXXXXXXX           ',
'  XXXXX               XXXXXX               XXXXX            XXXXX             ',
'    XXX       D     XXXXXXXXXXX    XXXX                D                      ',
'    XX                    XXXX       XXXX                                     ',
'             D                                                                ',
]

fourth = [
'                                                                              ',
'                                                                              ',
'                                                                              ',
'                                                                              ',
'        P                   XXXXX          D                                  ',
'           XXXXX              XXXXX                                           ',
'       XXXXXXXXXXXXX            XX        XX            D                     ',
'     XXXXXXXXXXXXXX                    XXXXX                                  ',
'     XXXXXXXXXXXX       D                XX         XXX                       ',
'     XXXXXXXXXXXX                 K            XXXXXXXXX                      ',
'         XXXXXXX      XXX                       XXXXXXXXXX                    ',
'                     XXXX                         XXXXXXX                     ',
'                      XX                           XXX                        ',
'                                                                              ',
'                                                                              ',
'                    D     XXXXXXXXXXXXXXXXXXXXX       D                       ',
'                           XXXXXXXXXXXXXXXXX                                  ',
'                              XXXXXXXXXXXXX            XX                     ',
'                              XXXXXX                XXXXXXX                   ',
'                               XXXX              XXXXXXXXXXXX                 ',
'                                                   XXXXXXXXXX                 ',
'                                                      XXXXXX                  ',
'                                                        XXX                   ',
'                                                                              ',
'                                                                              ',
'                                                                              ',
'                                                                              ',
'                                                                              ',
]
